package com.webservices;
//Generated by MyEclipse

public class HelloWebServiceImpl implements IHelloWebService {
	
	public String example(String message) {
		return "example:"+message;
	}
	public  String getName(){
		return "hello:";
	}
	public String test(String name) {
		return "test:"+name;
	}
	public String test2(String name) {
		return getName()+name;
	}
	
}